// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  Events: 'Events', // UNUSED
  'Clicca qui per iscriverti': 'Click here to register now', // UNUSED
  'Dettagli Evento': 'Event Details',
  'Entra qui per aggiornamenti': 'Enter here for updates', // UNUSED
  'Meet My Admin': 'Meet My Admin',
  'Iscrizioni chiuse. Grazie a tutti. Seguiranno prestissimo aggiornamenti.': 'Registrations closed. Thank you all. Updates will follow very soon.',
  'Per ulteriori informazioni chiedi qui': 'For more information ask here',
  'Quando: 16/09/2021 ore 21:00': 'When: 09/16/2021 at 21:00',
  'L\'evento annuale organizzato da PoliNetwork con Matricole ed Admin di tutte le facoltà. Un\'occasione per incontrarsi, chiacchierare, conoscersi davanti a una birra e stringere amicizie per affrontare insieme il nuovo percorso di studio, ma anche per farci qualsiasi domanda!': 'The annual event organized by PoliNetwork with Freshmen and Admin of all faculties. An opportunity to meet, chat, get to know each other over a beer and make friends to face the new study path together, but also to ask any questions!', // UNUSED
  '(current)': '(current)',
  'Perché c\'è un limite al numero di partecipanti?': 'Why is there a limit on the number of participants?', // UNUSED
  'A causa delle restrizioni anti Covid-19 il locale ha imposto questo limite': 'Because of restrictions against Covid-19, the venue set this limit', // UNUSED
  'Perché sarà data priorità ad Admin e Matricole?': 'Why are Freshmen and Admins prioritized?', // UNUSED
  'A causa del limite al numero di persone abbiamo deciso di dare priorità alle matricole, che potranno anche confrontarsi con noi Admin': 'Because of the limit on the number of people, we decided to prioritize Freshmen, that will also be able to interact whith Admins', // UNUSED
  'Perché il form mi dice che non ho l\'autorizzazione ad accedere?': 'Why does the form tell me that I am not authorized to compile it?', // UNUSED
  'Devi accedere utilizzando l\'account Microsoft fornito dal Politecnico (nome.cognome@mail.polimi.it oppure codicepersona@polimi.it), questo è per assicurarci che tu sia effettivamente uno studente del Politecnico': 'You have to sign in using the Microsoft account provided by Politecnico (name.surname@mail.polimi.it oppure personcode@polimi.it), this is to ensure that you actually are a Politecnico student', // UNUSED
  'Dovrò esibire il Green Pass all\'ingresso del locale?': 'Will I need to show the Green Pass upon entering the venue?', // UNUSED
  'Sì, dato che gran parte delle pertinenze del locale sono al chiuso e comunque non sarà possibile rispettare le regole di distanziamento, il Green Pass o un certificato equivalente sarà obbligatorio. È inoltre consigliato portare con sé un documento di identità con foto e in corso di validità': 'Yes, given that most of the premises are indoors and in any case it will not be possible to respect the distancing rules, the Green Pass or an equivalent certificate will be mandatory. It is also advisable to bring a valid photo ID with you', // UNUSED
  'Quali sono e come verranno trattati i dati inviati tramite il form di iscrizione?': 'What are the data we collect and how will we handle them?', // UNUSED
  'Il form raccoglie il Codice Persona (equivalente all\'email con Nome e Cognome) e il tag Telegram o numero di telefono. Entro 24 ore dal termine dell\'evento tutti i dati saranno cancellati. Utilizzeremo queste informazioni per accertare l\'appartenenza al Politecnico di Milano come Matricole o Admin e per mandare comunicazioni inerenti l\'evento. I dati sono gestiti da Diego Aldarese, organizzatore dell\'evento. Trovate i contatti di Diego nella pagina contatti.': 'The form collects the Person Code (equivalent to the email with name and surname) and the Telegram tag or phone number. All data will be ereased whithin 24 hours after the end of the event. We\'ll use this information to determine wheather or not you are a Freshmen or an Admin at Politecnico di Milano and to send communications relevant to the event. The data handler will be Diego Aldarese, organizer of the event. You can find Diego\'s contact information in the \'contact us\' webpage.', // UNUSED
  Contatti: 'Contacts',
  'Questo sito non è affiliato al Politecnico di Milano': 'This site is not affiliated with the Politecnico di Milano',
  'Tutti i nostri contatti e le nostre pagine social si trovano facilmente sul nostro': 'All our contacts and our social pages can be easily found on our', // UNUSED
  'Scrivi all\'organizzatore (Diego)': 'Text the organizer (Diego) by',
  'cliccando qui': 'clicking here',
  'sito web principale': 'main website',
  'Il numero massimo di partecipanti è limitato e sarà data priorità ad Admin e Matricole': 'The maximum number of participants is limited and priority will be given to Admin and Freshmen', // UNUSED
  'Entra qui per aggiornamenti (riservato agli iscritti)': 'Enter here for updates (reserved for members)'
}
