// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
	Events: 'Events', // UNUSED
	'Clicca qui per iscriverti': 'Click here to register now',
	'Dettagli Evento': 'Event Details',
	'Entra qui per aggiornamenti': 'Enter here for updates',
	'Meet My Admin': 'Meet My Admin',
	'Numero massimo di partecipanti: 60': 'Maximum number of participants: 60',
	'Per ulteriori informazioni chiedi qui': 'For more information ask here',
	'Quando: 16/09/2021 ore 21:00': 'When: 09/16/2021 at 21:00',
	'L\'evento annuale organizzato da PoliNetwork con Matricole ed Admin di tutte le facoltà': 'The annual event organized by PoliNetwork with Freshmen and Admin of all faculties',
	'(current)': '(current)',
	Contatti: 'Contacts',
	'Questo sito non è affiliato al Politecnico di Milano': 'This site is not affiliated with the Politecnico di Milano',
	'Tutti i nostri contatti e le nostre pagine social si trovano facilmente sul nostro': 'All our contacts and our social pages can be easily found on ours'
}
