// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  '(current)': '(current)',
  Contatti: 'Contacts', // contact // touch // connection // connexion
  'Dettagli Evento': 'Event Details',
  'Entra qui per aggiornamenti (riservato agli iscritti)': 'Enter here for updates (reserved for members)',
  'Meet My Admin': 'Meet My Admin',
  'Per ulteriori informazioni chiedi qui': 'For more information ask here',
  'Quando: 16/09/2021 ore 21:00': 'When: 09/16/2021 at 21:00',
  'Questo sito non è affiliato al Politecnico di Milano': 'This site is not affiliated with the Politecnico di Milano',
  'Scrivi all\'organizzatore (Diego)': 'Write to the organizer (Diego)',
  'cliccando qui': 'clicking here',
  'sito web principale': 'main website'
}
