// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  '(current)': '(current)',
  Contatti: 'Contatti',
  'Dettagli Evento': 'Dettagli Evento',
  'Entra qui per aggiornamenti (riservato agli iscritti)': 'Entra qui per aggiornamenti (riservato agli iscritti)',
  'Meet My Admin': 'Meet My Admin',
  'Per ulteriori informazioni chiedi qui': 'Per ulteriori informazioni chiedi qui',
  'Quando: 16/09/2021 ore 21:00': 'Quando: 16/09/2021 ore 21:00',
  'Questo sito non è affiliato al Politecnico di Milano': 'Questo sito non è affiliato al Politecnico di Milano',
  'Scrivi all\'organizzatore (Diego)': 'Scrivi all\'organizzatore (Diego)',
  'cliccando qui': 'cliccando qui',
  'sito web principale': 'sito web principale'
}
