// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  'Clicca qui per iscriverti': 'Clicca qui per iscriverti',
  'Dettagli Evento': 'Dettagli Evento',
  'Entra qui per aggiornamenti': 'Entra qui per aggiornamenti',
  'Meet My Admin': 'Meet My Admin',
  'Numero massimo di partecipanti: 60': 'Numero massimo di partecipanti: 60',
  'Per ulteriori informazioni chiedi qui': 'Per ulteriori informazioni chiedi qui',
  'Quando: 16/09/2021 ore 21:00': 'Quando: 16/09/2021 ore 21:00',
  'L\'evento annuale organizzato da PoliNetwork con Matricole ed Admin di tutte le facoltà': 'L\'evento annuale organizzato da PoliNetwork con Matricole ed Admin di tutte le facoltà',
  '(current)': '(current)',
  Contatti: 'Contatti',
  'Questo sito non è affiliato al Politecnico di Milano': 'Questo sito non è affiliato al Politecnico di Milano',
  'Tutti i nostri contatti e le nostre pagine social si trovano facilmente sul nostro': 'Tutti i nostri contatti e le nostre pagine social si trovano facilmente sul nostro'
}
