// generated by nuxt-i18n-easy
/* eslint-disable */
export default {
  'Eventi': 'Eventi', // UNUSED
  'Clicca qui per iscriverti': 'Clicca qui per iscriverti', // UNUSED
  'Dettagli Evento': 'Dettagli Evento',
  'Entra qui per aggiornamenti': 'Entra qui per aggiornamenti', // UNUSED
  'Meet My Admin': 'Meet My Admin',
  'Grazie a tutti per essere venuti! Ci vediamo la prossima volta!': 'Grazie a tutti per essere venuti! Ci vediamo la prossima volta!',
  'Per ulteriori informazioni chiedi qui': 'Per ulteriori informazioni chiedi qui',
  'Quando: 15 settembre 2022 ore 21:00': 'Quando: 15 settembre 2022 ore 21:00',
  'L\'evento annuale organizzato da PoliNetwork con Matricole ed Admin di tutte le facoltà. Un\'occasione per incontrarsi, chiacchierare, conoscersi davanti a una birra e stringere amicizie per affrontare insieme il nuovo percorso di studio, ma anche per farci qualsiasi domanda!': 'L\'evento annuale organizzato da PoliNetwork con Matricole ed Admin di tutte le facoltà. Un\'occasione per incontrarsi, chiacchierare, conoscersi davanti a una birra e stringere amicizie per affrontare insieme il nuovo percorso di studio, ma anche per farci qualsiasi domanda!', // UNUSED
  '(current)': '(current)',
  'Perché c\'è un limite al numero di partecipanti?': 'Perché c\'è un limite al numero di partecipanti?', // UNUSED
  'A causa delle restrizioni anti Covid-19 il locale ha imposto questo limite': 'A causa delle restrizioni anti Covid-19 il locale ha imposto questo limite', // UNUSED
  'Perché sarà data priorità ad Admin e Matricole?': 'Perché sarà data priorità ad Admin e Matricole?', // UNUSED
  'A causa del limite al numero di persone abbiamo deciso di dare priorità alle matricole, che potranno anche confrontarsi con noi Admin': 'A causa del limite al numero di persone abbiamo deciso di dare priorità alle matricole, che potranno anche confrontarsi con noi Admin', // UNUSED
  'Perché il form mi dice che non ho l\'autorizzazione ad accedere?': 'Perché il form mi dice che non ho l\'autorizzazione ad accedere?', // UNUSED
  'Devi accedere utilizzando l\'account Microsoft fornito dal Politecnico (nome.cognome@mail.polimi.it oppure codicepersona@polimi.it), questo è per assicurarci che tu sia effettivamente uno studente del Politecnico': 'Devi accedere utilizzando l\'account Microsoft fornito dal Politecnico (nome.cognome@mail.polimi.it oppure codicepersona@polimi.it), questo è per assicurarci che tu sia effettivamente uno studente del Politecnico', // UNUSED
  'Dovrò esibire il Green Pass all\'ingresso del locale?': 'Dovrò esibire il Green Pass all\'ingresso del locale?', // UNUSED
  'Sì, dato che gran parte delle pertinenze del locale sono al chiuso e comunque non sarà possibile rispettare le regole di distanziamento, il Green Pass o un certificato equivalente sarà obbligatorio. È inoltre consigliato portare con sé un documento di identità con foto e in corso di validità': 'Sì, dato che gran parte delle pertinenze del locale sono al chiuso e comunque non sarà possibile rispettare le regole di distanziamento, il Green Pass o un certificato equivalente sarà obbligatorio. È inoltre consigliato portare con sé un documento di identità con foto e in corso di validità', // UNUSED
  'Quali sono e come verranno trattati i dati inviati tramite il form di iscrizione?': 'Quali sono e come verranno trattati i dati inviati tramite il form di iscrizione?', // UNUSED
  'Il form raccoglie il Codice Persona (equivalente all\'email con Nome e Cognome) e il tag Telegram o numero di telefono. Entro 24 ore dal termine dell\'evento tutti i dati saranno cancellati. Utilizzeremo queste informazioni per accertare l\'appartenenza al Politecnico di Milano come Matricole o Admin e per mandare comunicazioni inerenti l\'evento. I dati sono gestiti da Diego Aldarese, organizzatore dell\'evento. Trovate i contatti di Diego nella pagina contatti.': 'Il form raccoglie il Codice Persona (equivalente all\'email con Nome e Cognome) e il tag Telegram o numero di telefono. Entro 24 ore dal termine dell\'evento tutti i dati saranno cancellati. Utilizzeremo queste informazioni per accertare l\'appartenenza al Politecnico di Milano come Matricole o Admin e per mandare comunicazioni inerenti l\'evento. I dati sono gestiti da Diego Aldarese, organizzatore dell\'evento. Trovate i contatti di Diego nella pagina contatti.', // UNUSED
  'Contatti': 'Contatti',
  'Questo sito non è affiliato al Politecnico di Milano': 'Questo sito non è affiliato al Politecnico di Milano',
  'Tutti i nostri contatti e le nostre pagine social si trovano facilmente sul nostro': 'Tutti i nostri contatti e le nostre pagine social si trovano facilmente sul nostro', // UNUSED
  'Scrivi al responsabile eventi del network, trovi il contatto ': 'Scrivi al responsabile eventi del network, trovi il contatto ',
  'cliccando qui': 'cliccando qui',
  'sito web principale': 'sito web principale',
  'Il numero massimo di partecipanti è limitato e sarà data priorità ad Admin e Matricole': 'Il numero massimo di partecipanti è limitato e sarà data priorità ad Admin e Matricole', // UNUSED
  'Entra qui per aggiornamenti (riservato agli iscritti)': 'Entra qui per aggiornamenti (riservato agli iscritti)',
  'Entra qui per iscriverti (Solo se pensi di poter venire)': 'Entra qui per iscriverti (Solo se pensi di poter venire)',
  'Gli eventi del network!': 'Gli eventi del network!',
  'L\'evento annuale di incontro fra matricole e admin': 'L\'evento annuale di incontro fra matricole e admin',
  'Il network diventa associazione e vi invita a festeggiare!': 'Il network diventa associazione e vi invita a festeggiare!',
  'Grazie a tutti per essere venuti!': 'Grazie a tutti per essere venuti!',
  'Ci vediamo la prossima volta!': 'Ci vediamo la prossima volta!',
  'Terminato': 'Terminato',
  'Errore': 'Errore',
  'Torna alla Home': 'Torna alla Home',
  'A causa delle dimensioni del locale e della presenza di altri clienti oltre a noi, è imposto un limite': 'A causa delle dimensioni del locale e della presenza di altri clienti oltre a noi, è imposto un limite',
  'In arrivo': 'In arrivo',
  'Passati': 'Passati',
  'Al Completo': 'Al Completo',
  'Purtoppo siamo al completo,': 'Purtoppo siamo al completo,',
  'se si liberaranno dei posti vi faremo sapere!': 'se si liberaranno dei posti vi faremo sapere!'
}
